name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
- prasadnevase
body:
- id: issuebody
  type: markdown
  attributes:
    value: "Thanks for taking the time to fill out this bug!"
- type: markdown
  attributes:
    label: "What's wrong?"
